version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    container_name: corpalert-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: corpalert
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - corpalert-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server
    container_name: corpalert-server
    volumes:
      - ./server:/app
    working_dir: /app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:mysecretpassword@db:5432/corpalert
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0 --port=5000

  client:
    build: ./client
    container_name: corpalert-client
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "5173:5173"
    depends_on:
      - server
    command: npm run dev -- --host

volumes:
  corpalert-pgdata:
